---
- hosts: dbserver
  vars:
    - http_port: 8080
    - tomcat_version: 10.1.8

  tasks:
    - name: Install OpenJDK
      apt: name=openjdk-11-jdk state=latest

    - name: add group "tomcat"
      group: name=tomcat

    - name: add user "tomcat"
      user: name=tomcat group=tomcat createhome=yes
      become: true

    - name: Download Tomcat
      get_url: url=https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.8/bin/apache-tomcat-10.1.8.tar.gz   dest=/opt/apache-tomcat-10.1.8.tar.gz
    - name: Extract Tomcat archive
      command: tar zxvf /opt/apache-tomcat-10.1.8.tar.gz -C /opt/ creates=/opt/apache-tomcat-10.1.8
  
    - name: Change ownership of Tomcat installation
      file: path=/opt/apache-tomcat-10.1.8  owner=tomcat group=tomcat state=directory recurse=yes

    - name: Change the working directory to Tomcat Apache before running Tomcat Apache
      shell: ./startup.sh
      args:
       chdir: /opt/apache-tomcat-10.1.8/bin/
      become: true
      become_user: tomcat

